### GET ALL
GET http://localhost:3000/api/showCategory

### GET ONE
GET http://localhost:3000/api/showCategory/2

### POST  
POST http://localhost:3000/api/showCategory
Content-Type: application/json

{
    "description": "Funcion 3D",
    "price": 5000
}

### PUT (modificacion completa)
PUT http://localhost:3000/api/showCategory/1
Content-Type: application/json

{
    "description": "Funcion 3D",
    "price": 10000
}

### DELETE 
DELETE http://localhost:3000/api/showCategory/1
