### GET ALL
GET http://localhost:3000/api/Seat

### GET ONE
GET http://localhost:3000/api/Seat/1

### POST  
POST http://localhost:3000/api/Seat
Content-Type: application/json

{
    "row": 10,
    "number": 8
}

### PUT (modificacion completa)
PUT http://localhost:3000/api/Seat/1
Content-Type: application/json

{
    "row": 12,
    "number": 5
}

### PATCH (modificacion parcial o incremental)
PATCH http://localhost:3000/api/Seat/1
Content-Type: application/json

{
    "number": 8
}

### DELETE 
DELETE http://localhost:3000/api/Seat/1