### GET ALL
GET http://localhost:3000/api/movies

### GET ONE
GET http://localhost:3000/api/movies/1

### POST  
POST http://localhost:3000/api/movies
Content-Type: application/json

{
    "name": "Star Wars: Una Nueva Esperanza (Aniversario)",
    "duration": 121,
    "synopsis": "Únete a la celebración del aniversario de la saga que cambió la galaxia. Proyección especial remasterizada de la película original que lo empezó todo. ¡Que la Fuerza te acompañe!",
    "url": "https://m.media-amazon.com/images/I/71Um2ouHp-L._AC_SY879_.jpg"
}

### PUT (modificacion completa)
PUT http://localhost:3000/api/movies/1
Content-Type: application/json

{
    "name": "F1 the movie",
    "duration": 155
}

### PATCH (modificacion parcial o incremental)
PATCH http://localhost:3000/api/movies/1
Content-Type: application/json

{
    "name": "avengers endgame"
}

### DELETE 
DELETE http://localhost:3000/api/movies/1
