### GET ALL
GET http://localhost:3000/api/movies

### GET ONE
GET http://localhost:3000/api/movies/1

### POST  
POST http://localhost:3000/api/movies
Content-Type: application/json

{
    "name": "F1 The Movie",
    "duration": 180,
    "synopsis": "F1 The Movie is a documentary that takes you behind the scenes of the Formula 1 racing world, showcasing the intense competition and the lives of the drivers.",
    "url": "https://www.dropbox.com/scl/fi/c7x7n3p4vydlir57jf4ti/MV5BZTYwYjJhNzYtY2ZiZS00ZmYxLWJkZjctYjRlNGIxYjI3ZTU0XkEyXkFqcGc-._V1_FMjpg_UX1000_.jpg?rlkey=tzcvo8fx6dbv23u5l75uvttb2&st=927v85x9&dl=0"
}

### PUT (modificacion completa)
PUT http://localhost:3000/api/movies/1
Content-Type: application/json

{
    "name": "F1 the movie",
    "duration": 155
}

### PATCH (modificacion parcial o incremental)
PATCH http://localhost:3000/api/movies/1
Content-Type: application/json

{
    "name": "avengers endgame"
}

### DELETE 
DELETE http://localhost:3000/api/movies/1
