### GET ALL
GET http://localhost:3000/api/users

### GET ONE
GET http://localhost:3000/api/users/1

### POST  
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "username": "titoNICO7",
    "name": "Nicolas",
    "surname": "Herrera",
    "email": "nico@herrera.com",
    "birthdate": "2003-03-27",
    "password": "123tito"
}

### PUT (modificacion completa)
PUT http://localhost:3000/api/users/1
Content-Type: application/json

{
    "username": "titoNICO3",
    "name": "Nico",
    "surname": "Herrera2",
    "email": "nico@herrera27.com",
    "birthdate": "2003-03-28",
    "password": "1234tito"
    
}

### PATCH (modificacion parcial o incremental)
PATCH http://localhost:3000/api/users/1
Content-Type: application/json

{
    "name": "tito3",
    "surname": "NICO7"
}

### DELETE 
DELETE http://localhost:3000/api/users/1