### GET ALL
GET http://localhost:3000/api/users


### GET ONE
GET http://localhost:3000/api/users/2

### POST  
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "username": "titoNICO7253433",
    "name": "Nicolas23",
    "surname": "Herrera23",
    "email": "nico@herrera.com23543e",
    "birthdate": "2003-03-272",
    "password": "123tit23"
}

### PUT (modificacion completa)
PUT http://localhost:3000/api/users/5
Content-Type: application/json

{
    "username": "titoNICO3",
    "name": "Nico",
    "surname": "Herrera2",
    "email": "nico@herrera27.com",
    "birthdate": "2003-03-28",
    "password": "1234tito"
    
}


### DELETE
DELETE http://localhost:3000/api/users/1