### GET ALL
GET http://localhost:3000/api/rooms

### GET ONE
GET http://localhost:3000/api/rooms/1

### POST  
POST http://localhost:3000/api/rooms
Content-Type: application/json

{
    "name": "sala 1",
    "capacity": 85
}

### PUT (modificacion completa)
PUT http://localhost:3000/api/rooms/1
Content-Type: application/json

{
    "name": "sala me",
    "capacity": 100 
}

### PATCH (modificacion parcial o incremental)
PATCH http://localhost:3000/api/rooms/1
Content-Type: application/json

{
    "name": "sala dos",
}

### DELETE 
DELETE http://localhost:3000/api/rooms/1
