###obtener todos los adoptiones 
GET http://localhost:3000/api/adoption

###obtener un adoption 
GET http://localhost:3000/api/adoption/2

###crear un nuevo adoption
POST http://localhost:3000/api/adoption
Content-Type: application/json

{
  "comments": "adoption 2", 
  "animal": 6,
  "person": 4,
  "adoption_date": "2020-03-03"
}

### modificar un adoption (PUT)
PUT http://localhost:3000/api/adoption/1
Content-Type: application/json

{
  "comments": "adoptionsss", 
  "person": 4,
  "animal": 6,
  "adoption_date": "2024-03-03"
}

### modificar un adoption (PATCH - recurso parcial)
PATCH http://localhost:3000/api/adoption/1
Content-Type: application/json

{
  "comments": "adoption patch test",
}

### borrar un adoption
DELETE http://localhost:3000/api/adoption/1